name: Nashipae
title: https://media.licdn.com/dms/image/v2/D4E03AQF7gQzd7UaNVw/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1724758204659?e=1758153600&v=beta&t=SeQizbk6aTqgO6yCnib4LhTTe7RjjxuS35_zB6Rv3Jk
theme: jekyll-theme-Minimal
